/**
 * Central permission registry.
 * Type-safe permission strings used for route guards and action-level checks.
 */

export const PERMISSIONS = [
  "dashboard.view_full",
  "dashboard.view_operational",
  "dashboard.view_personal",
  "customers.view",
  "customers.create",
  "customers.edit",
  "customers.delete",
  "vehicles.view",
  "vehicles.create",
  "vehicles.edit",
  "jobs.view_all",
  "jobs.view_operational",
  "jobs.view_assigned",
  "jobs.create",
  "jobs.edit_basic",
  "jobs.assign",
  "jobs.update_status",
  "jobs.add_notes",
  "jobs.upload_media",
  "quotes.view",
  "quotes.create",
  "quotes.edit",
  "quotes.convert",
  "pipeline.view",
  "pipeline.edit",
  "calendar.view",
  "calendar.edit",
  "media.view",
  "media.view_assigned",
  "media.upload",
  "media.manage",
  "services.view",
  "services.create",
  "services.edit",
  "services.delete",
  "invoices.view",
  "invoices.manage",
  "analytics.view_full",
  "team.view",
  "team.manage",
  "notifications.view",
  "settings.manage",
  "permissions.manage",
  "audit_logs.view",
  "chat.view",
  "chat.send",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

/** Permission metadata for UI or docs. */
export const PERMISSION_LABELS: Record<Permission, string> = {
  "dashboard.view_full": "View full dashboard",
  "dashboard.view_operational": "View operational dashboard",
  "dashboard.view_personal": "View personal (My Jobs) dashboard",
  "customers.view": "View customers",
  "customers.create": "Create customers",
  "customers.edit": "Edit customers",
  "customers.delete": "Delete customers",
  "vehicles.view": "View vehicles",
  "vehicles.create": "Create vehicles",
  "vehicles.edit": "Edit vehicles",
  "jobs.view_all": "View all jobs",
  "jobs.view_operational": "View operational jobs",
  "jobs.view_assigned": "View assigned jobs only",
  "jobs.create": "Create jobs",
  "jobs.edit_basic": "Edit job basics",
  "jobs.assign": "Assign jobs",
  "jobs.update_status": "Update job status",
  "jobs.add_notes": "Add job notes",
  "jobs.upload_media": "Upload job media",
  "quotes.view": "View quotes",
  "quotes.create": "Create quotes",
  "quotes.edit": "Edit quotes",
  "quotes.convert": "Convert quotes",
  "pipeline.view": "View pipeline",
  "pipeline.edit": "Edit pipeline",
  "calendar.view": "View calendar",
  "calendar.edit": "Edit calendar",
  "media.view": "View all media",
  "media.view_assigned": "View assigned job media",
  "media.upload": "Upload media",
  "media.manage": "Manage media library",
  "services.view": "View services",
  "services.create": "Create services",
  "services.edit": "Edit services",
  "services.delete": "Delete services",
  "invoices.view": "View invoices",
  "invoices.manage": "Manage invoices",
  "analytics.view_full": "View full analytics",
  "team.view": "View team",
  "team.manage": "Manage team",
  "notifications.view": "View notifications",
  "settings.manage": "Manage settings",
  "permissions.manage": "Manage permissions",
  "audit_logs.view": "View audit logs",
  "chat.view": "View chat",
  "chat.send": "Send chat messages",
} as Record<Permission, string>;

export function isPermission(value: string): value is Permission {
  return PERMISSIONS.includes(value as Permission);
}
